<?php

namespace AppBundle\Entity;

/**
 * QuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
abstract class ExtendRepository extends \Doctrine\ORM\EntityRepository
{
    abstract public function findAllByParentId($parentId);
}
