<?php

namespace AppBundle\Entity;

use AppBundle\Entity\ExtendRepository;

/**
 * VariantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VariantRepository extends ExtendRepository
{
    public function findAllByParentId($parentId) {
        try {
            return $query = $this->getEntityManager()
                ->createQueryBuilder()
                ->select('v')
                ->from('AppBundle:Variant', 'v')
                ->leftJoin('AppBundle:Question', 'q', 'WITH', 'v.question = :questionId')
                ->where('q.id = :questionId')
                ->setParameter('questionId', $parentId)
                ->getQuery()
                ->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return $e;
        }
//SELECT * FROM fora_soft_test.variant where question_id = 1;
    }
}
